version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - heart_rate_service
      - users_service

  heart_rate_service:
    image: python:3.8
    ports:
      - "5000:5000"
    command: >
      sh -c "export PYTHONPATH=/src:$PYTHONPATH && pip install -r /src/api/requirements.txt && python3 /src/api/heart_rate.py"
    volumes:
      - ./src/api/:/src/api/
      - ./src/middleware/:/src/middleware
      - ./src/models/:/src/models
    depends_on:
      - mongodb

  users_service:
    image: python:3.8
    ports:
      - "5001:5001"
    command: >
      sh -c "export PYTHONPATH=/src:$PYTHONPATH && pip install -r /src/api/requirements.txt && python3 /src/api/users.py"
    volumes:
      - ./src/api/:/src/api
      - ./src/middleware/:/src/middleware
      - ./src/models/:/src/models
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "4000:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --bind_ip_all --noauth
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
