version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sensors_service
      - users_service

  sensors_service:
    image: python:3.8
    ports:
      - "5000:5000"
    command: >
      sh -c "export PYTHONPATH=/src:$PYTHONPATH && pip install -r /src/apis/requirements.txt && python3 /src/apis/sensors.py"
    volumes:
      - ./src/apis/:/src/apis/
      - ./src/middleware/:/src/middleware
      - ./src/models/:/src/models
    env_file:
      - .env
    depends_on:
      - mongodb

  users_service:
    image: python:3.8
    ports:
      - "5001:5001"
    command: >
      sh -c "export PYTHONPATH=/src:$PYTHONPATH && pip install -r /src/apis/requirements.txt && python3 /src/apis/users.py"
    volumes:
      - ./src/apis/:/src/apis
      - ./src/middleware/:/src/middleware
      - ./src/models/:/src/models
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "4000:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --bind_ip_all --noauth
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
