version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - heart_rate_service
      - users_service

  heart_rate_service:
    image: python:3.8
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r /app/requirements.txt && python /app/heart_rate.py"
    volumes:
      - ./src/api/:/app
      - .env:/app/.env
    depends_on:
      - mongodb

  users_service:
    image: python:3.8
    ports:
      - "5001:5001"
    command: >
      sh -c "pip install -r /app/requirements.txt && python /app/users.py"
    volumes:
      - ./src/api/:/app
      - .env:/app/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "4000:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: mongod --bind_ip_all --noauth
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
