#https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose
services:
  web:
    build: .
    ports:
      - "8000:5000"
    networks:
      vpcbr:
        ipv4_address: 10.42.0.2
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.42.0.0/16
         gateway: 10.42.0.1